apiVersion: apps/v1
kind: Deployment
metadata:
  name: cadvisor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: cadvisor
  replicas: 1
  template:
    metadata:
      labels:
        app: cadvisor
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - hostname
      containers:
      - name: cadvisor
        image: google/cadvisor:latest
        securityContext:
          capabilities:
            drop: ["all"]
            add: ["NET_BIND", "SYS_ADMIN", "NET_ADMIN"]
        command:
          - --docker="tcp://172.17.0.1:2375" #if dockerd run via tcp
          - --docker="unix:///var/run/docker.sock" #if dockerd run via unix socket
          - --docker_root="/var/lib/docker" #DEPRECATED: docker root is read from docker info (this is a fallback, default: /var/lib/docker) (default "/var/lib/docker")
          - --docker-tls #use TLS to connect to docker
          - --docker-tls-cert="cert.pem" #client certificate for TLS-connection with docker
          - --docker-tls-key="key.pem" #private key for TLS-connection with docker
          - --docker-tls-ca="ca.pem" #trusted CA for TLS-connection with docker
        resource:
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - mountPath: /rootfs
            name: root-volume
          - mountPath: /var/run
            name: run-volume
          - mountPath: /sys
            name: sys-volume
          - mountPath: /var/lib/docker/
            name: docker-volume
          - mountPath: /dev/disk/
            name: disk-volume
      volumes:
      - name: root-volume
        hostPath:
          path: /
      - name: root-volume
        hostPath:
          path: /var/run
      - name: run-volume
        hostPath:
          path: /sys
      - name: docker-volume
        hostPath:
          path: /var/lib/docker/
      - name: disk-volume
        hostPath:
          path: /dev/disk/

      # imagePullSecrets:
      # - name: image-secret
      
