version: '3.9'
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: cadvisor
    hostname: cadvisor-{{Node.Hostname}}
    cap_add:
      - ALL
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    deploy:
      mode: global
    ports:
    - 8080:8080
    command:
      - --docker=tcp://172.17.0.1:2375 #if dockerd run via tcp
      - --docker=unix:///var/run/docker.sock #if dockerd run via unix socket
      - --docker_root=/var/lib/docker #DEPRECATED: docker root is read from docker info (this is a fallback, default: /var/lib/docker) (default "/var/lib/docker")
      - --docker-tls #use TLS to connect to docker
      - --docker-tls-cert=cert.pem #client certificate for TLS-connection with docker
      - --docker-tls-key=key.pem #private key for TLS-connection with docker
      - --docker-tls-ca=ca.pem #trusted CA for TLS-connection with docker
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /dev/disk/:/dev/disk:ro
    #mount certificate file
    - ./cert.pem:./cert.pem
    - ./key.pem:./key.pem
    - ./ca.pem:./ca.pem
    networks:
      - networkName

# docker network create -d overlay --scope swarm --attachable networkName
networks:
  networkName:
    external: true
    # attachable: true

